"""Terraform import command generator."""

import os
from pathlib import Path
from typing import List, Optional, TextIO
import logging

from ...domain.entities import (
    Group,
    Project,
    TerraformResource,
    TerraformModule,
)

logger = logging.getLogger(__name__)


class ImportGenerator:
    """Generator for Terraform import commands and configuration files."""

    def generate_import_commands(
        self,
        resources: List[TerraformResource],
        output_file: Optional[Path] = None
    ) -> List[str]:
        """Generate Terraform import commands.

        Args:
            resources: List of resources to import
            output_file: Optional file to write commands to

        Returns:
            List of import commands
        """
        commands = []

        for resource in resources:
            if resource.import_id:
                cmd = resource.get_import_command()
                if cmd:
                    commands.append(cmd)

        logger.info(f"Generated {len(commands)} import commands")

        if output_file:
            self._write_import_script(commands, output_file)

        return commands

    def _write_import_script(self, commands: List[str], output_file: Path) -> None:
        """Write import commands to a shell script.

        Args:
            commands: List of import commands
            output_file: Output file path
        """
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, 'w') as f:
            f.write('#!/bin/bash\n')
            f.write('# Terraform import script for GitLab resources\n')
            f.write('# Generated by gitlab-terraform-importer\n\n')
            f.write('set -e\n\n')

            for cmd in commands:
                f.write(f'{cmd}\n')

        # Make executable
        os.chmod(output_file, 0o755)
        logger.info(f"Import script written to: {output_file}")

    def generate_resource_files(
        self,
        groups: List[Group],
        projects: List[Project],
        output_dir: Path
    ) -> List[Path]:
        """Generate Terraform resource configuration files.

        Args:
            groups: List of groups
            projects: List of projects
            output_dir: Output directory

        Returns:
            List of generated file paths
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        generated_files = []

        # Generate provider configuration
        provider_file = output_dir / "provider.tf"
        self._generate_provider_file(provider_file)
        generated_files.append(provider_file)

        # Generate groups file
        if groups:
            groups_file = output_dir / "groups.tf"
            self._generate_groups_file(groups, groups_file)
            generated_files.append(groups_file)

        # Generate projects file
        if projects:
            projects_file = output_dir / "projects.tf"
            self._generate_projects_file(projects, projects_file)
            generated_files.append(projects_file)

        logger.info(f"Generated {len(generated_files)} Terraform files")
        return generated_files

    def _generate_provider_file(self, output_file: Path) -> None:
        """Generate provider configuration file.

        Args:
            output_file: Output file path
        """
        with open(output_file, 'w') as f:
            f.write('terraform {\n')
            f.write('  required_providers {\n')
            f.write('    gitlab = {\n')
            f.write('      source  = "gitlabhq/gitlab"\n')
            f.write('      version = "~> 17.0"\n')
            f.write('    }\n')
            f.write('  }\n')
            f.write('}\n\n')
            f.write('provider "gitlab" {\n')
            f.write('  # Configuration via environment variables:\n')
            f.write('  # - GITLAB_TOKEN\n')
            f.write('  # - GITLAB_BASE_URL (optional)\n')
            f.write('}\n')

    def _generate_groups_file(self, groups: List[Group], output_file: Path) -> None:
        """Generate groups configuration file.

        Args:
            groups: List of groups
            output_file: Output file path
        """
        with open(output_file, 'w') as f:
            for group in groups:
                self._write_group_resource(f, group)
                f.write('\n')

    def _generate_projects_file(self, projects: List[Project], output_file: Path) -> None:
        """Generate projects configuration file.

        Args:
            projects: List of projects
            output_file: Output file path
        """
        with open(output_file, 'w') as f:
            for project in projects:
                self._write_project_resource(f, project)
                f.write('\n')

    def _write_group_resource(self, f: TextIO, group: Group) -> None:
        """Write a group resource to file.

        Args:
            f: File handle
            group: Group entity
        """
        resource_name = group.get_terraform_resource_name()

        f.write(f'resource "gitlab_group" "{resource_name}" {{\n')
        f.write(f'  name        = "{self._escape_string(group.name)}"\n')
        f.write(f'  path        = "{group.path}"\n')

        if group.description:
            f.write(f'  description = "{self._escape_string(group.description)}"\n')

        f.write(f'  visibility_level = "{group.visibility}"\n')

        if group.parent_id:
            # Try to find parent resource reference
            parent_ref = self._get_parent_reference(group)
            if parent_ref:
                f.write(f'  parent_id   = {parent_ref}\n')
            else:
                f.write(f'  # parent_id = {group.parent_id}  # Manual reference needed\n')

        f.write('}\n')

    def _write_project_resource(self, f: TextIO, project: Project) -> None:
        """Write a project resource to file.

        Args:
            f: File handle
            project: Project entity
        """
        resource_name = project.get_terraform_resource_name()

        f.write(f'resource "gitlab_project" "{resource_name}" {{\n')
        f.write(f'  name        = "{self._escape_string(project.name)}"\n')
        f.write(f'  path        = "{project.path}"\n')

        if project.description:
            f.write(f'  description = "{self._escape_string(project.description)}"\n')

        # Namespace reference
        group_path = project.get_group_path()
        if group_path:
            group_resource = group_path.replace('/', '_').replace('-', '_').replace('.', '_')
            f.write(f'  namespace_id = gitlab_group.{group_resource}.id\n')
        else:
            f.write(f'  # namespace_id = {project.namespace_id}  # Manual reference needed\n')

        f.write(f'  visibility_level = "{project.visibility}"\n')

        if project.default_branch:
            f.write(f'  default_branch = "{project.default_branch}"\n')

        if project.topics:
            topics_str = ", ".join([f'"{topic}"' for topic in project.topics])
            f.write(f'  topics = [{topics_str}]\n')

        f.write(f'  issues_enabled = {str(project.issues_enabled).lower()}\n')
        f.write(f'  merge_requests_enabled = {str(project.merge_requests_enabled).lower()}\n')
        f.write(f'  wiki_enabled = {str(project.wiki_enabled).lower()}\n')
        f.write(f'  snippets_enabled = {str(project.snippets_enabled).lower()}\n')
        f.write(f'  container_registry_enabled = {str(project.container_registry_enabled).lower()}\n')

        if project.archived:
            f.write(f'  archived = true\n')

        f.write('}\n')

    def map_gitlab_to_terraform_resources(
        self,
        groups: List[Group],
        projects: List[Project]
    ) -> List[TerraformResource]:
        """Map GitLab entities to Terraform resources.

        Args:
            groups: List of groups
            projects: List of projects

        Returns:
            List of Terraform resources
        """
        resources = []

        # Map groups
        for group in groups:
            resource = TerraformResource(
                resource_type="gitlab_group",
                resource_name=group.get_terraform_resource_name(),
                attributes={
                    "name": group.name,
                    "path": group.path,
                    "description": group.description,
                    "visibility_level": group.visibility,
                },
                import_id=str(group.id),
            )
            resources.append(resource)

        # Map projects
        for project in projects:
            resource = TerraformResource(
                resource_type="gitlab_project",
                resource_name=project.get_terraform_resource_name(),
                attributes={
                    "name": project.name,
                    "path": project.path,
                    "description": project.description,
                    "visibility_level": project.visibility,
                },
                import_id=str(project.id),
            )
            resources.append(resource)

        return resources

    @staticmethod
    def _escape_string(s: Optional[str]) -> str:
        """Escape string for Terraform.

        Args:
            s: String to escape

        Returns:
            Escaped string
        """
        if not s:
            return ""
        return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

    @staticmethod
    def _get_parent_reference(group: Group) -> Optional[str]:
        """Get Terraform reference to parent group.

        Args:
            group: Group entity

        Returns:
            Terraform reference or None
        """
        if not group.parent_id:
            return None

        # Try to construct parent reference from full_path
        parts = group.full_path.split('/')
        if len(parts) > 1:
            parent_path = '/'.join(parts[:-1])
            parent_resource = parent_path.replace('/', '_').replace('-', '_').replace('.', '_')
            return f'gitlab_group.{parent_resource}.id'

        return None
